compile:
	/usr/lib/jvm/java-17-openjdk-amd64/bin/javac -d . -cp .:/usr/local/src/java-libs/fastutil-7.0.12.jar knucleotide.java


run:
	/usr/lib/jvm/java-17-openjdk-amd64/bin/java  -cp .:/usr/local/src/java-libs/fastutil-7.0.12.jar knucleotide 0 < ../../../knucleotide-input25000000.txt

